#mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring.profiles.active: database,xyplorer
server.port: 8081
#server.address=127.0.0.1
file-management-system:
  targetDir: 'D:\可删除2\1'



