spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          driver-class-name: org.sqlite.JDBC
          password: ''
          url: jdbc:sqlite:metadata/file-management-system.db
          username: ''
        firefox_browser:
          driver-class-name: org.sqlite.JDBC
          password: ''
          url: jdbc:sqlite:C:\Users\33719\AppData\Roaming\Mozilla\Firefox\Profiles\4pnxltcf.default-release-1668190769718\places.sqlite
          username: ''
